version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing Node.js dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the React application..."
      - npm run build
  post_build:
    commands:
      - echo "Post-build steps..."
      - echo "Build completed on $(date)"
artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: no
  name: react-app
  s3_bucket: cicd-pipeline-automation-final
