version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - cd $CODEBUILD_SRC_DIR
      - npm install

  build:
    commands:
      - echo Building the React application...
      - cd $CODEBUILD_SRC_DIR
      - npm run build

  post_build:
    commands:
      - echo Post-build steps...
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes

cache:
  paths:
    - node_modules/**/*
